python train.py \
        --output_dir ./train_models/bigbird-roberta-base \
        --model_type bigbird-roberta \
        --model_name_or_path google/bigbird-roberta-base \
        --train_file /kaggle/input/contract-review-dataset/train_separate_questions.json \
        --predict_file /kaggle/input/contract-review-dataset/test.json \
        --do_train \
        --version_2_with_negative \
        --learning_rate 1e-45 \
        --num_train_epochs 2 \
        --per_gpu_eval_batch_size=1  \
        --per_gpu_train_batch_size=1 \
        --max_seq_length 256 \
        --max_answer_length 256 \
        --doc_stride 128 \
        --save_steps 100 \
        --n_best_size 15 \
        --overwrite_output_dir
